/**
 * Connect client template generator
 */

/**
 * Generate connect-client.ts content
 */
export function generateConnectClientTemplate(): string {
  return `/**
 * API Client configuration for Connect-RPC
 * Using @theplant/fetch-middleware for advanced request/response handling
 * Reference: https://github.com/qor5/fe-infra/tree/main/packages/fetch-middleware
 */
import type { Interceptor } from '@connectrpc/connect'
import { createConnectTransport } from '@connectrpc/connect-web'
import {
  createFetchClient,
  formatProtoErrorMiddleware,
} from '@theplant/fetch-middleware'

// Use binary format (protobuf) instead of JSON
const useBinaryFormat = false

// API base URL from environment
const API_BASE_URL =
  (import.meta.env.VITE_API_BASE_URL as string | undefined) || ''

// Create fetch client for Connect-RPC
export const connectFetchClient = createFetchClient({
  fetchInit: {
    credentials: 'include',
    headers: {
      Accept: useBinaryFormat ? 'application/proto' : 'application/json',
      // Ensure server returns Connect standard error format with Details
      'X-Ensure-Connect-Error': 'true',
    },
  },
  middlewares: [formatProtoErrorMiddleware()],
})

/**
 * Error interceptor for global error handling
 * Catches all Connect-RPC errors and displays toast notifications
 */
const errorInterceptor: Interceptor = (next) => async (req) => {
  try {
    return await next(req)
  } catch (err) {
    // You can add custom error handling here
    // For example: toast notification, logging, etc.
    throw err
  }
}

/**
 * Create Connect transport with the fetch client
 * This transport is used by all Connect-RPC service clients
 */
export const transport = createConnectTransport({
  baseUrl: API_BASE_URL,
  useBinaryFormat,
  fetch: connectFetchClient, // Pass as fetch handler
  interceptors: [errorInterceptor], // Add global error interceptor
})
`;
}

/**
 * Generate top-level index.ts that aggregates all modules
 */
export function generateRpcServiceIndexTemplate(modules: string[]): string {
  // For single module, only export default
  if (modules.length === 1) {
    const moduleName = modules[0];
    return `// RPC Service Index - Aggregates all service modules
// DO NOT EDIT: This file is automatically generated

export * as ${moduleName}Service from './${moduleName}/services'
`;
  }

  // For multiple modules, aggregate into default export
  return `// RPC Service Index - Aggregates all service modules
// DO NOT EDIT: This file is automatically generated

${modules.map((module) => `import * as ${module}Service from './${module}/services'`).join("\n")}

export default {
${modules.map((module) => `  ...${module}Service,`).join("\n")}
}
`;
}
